version: 2

models:
  - name: customers
    description: "{{ doc('customers') }}"
    columns:
      - name: id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: first_order_date
        description: NULL when a customer has not yet placed an order.
  - name: stg_customers
    description: >
      # Purpose
      This model cleans up customer data
      ## Something else
      Blah blah
    columns:
      - name: id
        description: Primary key
        tests:
          - unique
          - not_null
  - name: stg_orders
    description: This model cleans up order data
    columns:
      - name: id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: status
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']
  - name: orders
    columns:
      - name: amount
        tests:
          - not_null

sources:
  - name: jaffle_shop
    database: raw
    freshness:
      warn_after: {count: 12, period: hour}
      error_after: {count: 24, period: hour}

    tables:
      - name: orders
        freshness:
          warn_after: {count: 3, period: hour}
          error_after: {count: 6, period: hour}
        loaded_at_field: _etl_loaded_at

      - name: customers

  - name: stripe
    database: raw
    freshness:
      warn_after: {count: 3, period: hour}
      error_after: {count: 6, period: hour}
    loaded_at_field: _batched_at
    tables:
      - name: payment
